### PR TITLE
BUG

### PR DESCRIPTION
**Pull request by mworkfun**
Fixed read year errors, duplicate variables and functions

### CODE REVIEW

**Comment by keble6** [comment]
Thanks! I am new to this and I can't find out (even with Google) how to test your changes locally before merging. I'm use github on a browser (Chrome on Chrome OS), so would prefer to stay with that.

**Comment by mworkfun** [comment]
Thank you for your reply! I have written the information in the attachment, please check.&nbsp; 










------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rob Wilson"<notifications@github.com&gt;; 
发送时间: 2020年11月11日(星期三) 晚上6:51
收件人: "keble6/pxt-DS3231"<pxt-DS3231@noreply.github.com&gt;; 
抄送: "??"<1123552240@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [keble6/pxt-DS3231] BUG (#1)






谢啦！我是新来的在合并之前，我无法找到如何在本地测试您的更改（即使使用Google）。我在浏览器上使用github（Chrome操作系统上的Chrome），所以我更愿意继续使用它。

—
你收到这个是因为你编写了这个线程。
直接回复此邮件，在GitHub上查看，或取消订阅.

**Comment by mworkfun** [comment]
View DS3231 datasheet page 11 to set time.

in main.ts code

wrong:
     ....
    export function dateTime(year: number, month: number, date: number, day: number, hour: number, minute: number, second: number){
        ....
        buf[7] = decToBcd(year);
        ...
    }



right:
    ...
    export function dateTime(year: number, month: number, date: number, day: number, hour: number, minute: number, second: number){
        ...
        buf[7] = (year -2000)/10*16 + (year -2000)%10;
        ...
    }

**Comment by keble6** [comment]
Thank you!

I agree that line 221 in main.ts must be changed to:

buf[7] = decToBcd(year-2000);


I have committed that change and also your suggested changes to pxt.json


However I think you made a mistake in the decToBcd replacement you made in 
your line 221 (It didn't pass the tests), so I kept the decToBcd usage.


I agree that my code can be tidied up! I was using blocks to do a lot of 
the testing, because I am not very good JS coder.


I might clean it up at some stage.
Thank you again for your help.


Here are the new test results for the time read-back:
TEST1 - set and read back time registers
1 PASS
2 PASS
3 PASS
4 PASS
5 PASS
6 PASS
7 PASS
TEST2 - set and read back time registers
1 PASS
2 PASS
3 PASS
4 PASS
5 PASS
6 PASS
7 PASS

Regards,Rob

**Comment by mworkfun** [comment]
Look at page 11 of the DS3231 data table and set the year table.The register of year is divided into the ten year (high eight bit) and year (low eight bit):

1.(year 2000)/10  ---> takes an integer, ten year

2.(year 2000)/10*16 --> takes an integer, ten year, then moves 8 bits to the left, turning it into a high eight bit data

3.(year 2000)%10 -- the remainder, year, used for the low eighth bit

4.buf[7] = (year 2000)/10*16 + (year 2000)%10 --> Sum of two data, and then writes to register of DS3231.

test IDE:
https://makecode.microbit.org/#editor

java sript:
DS3231.dateTime(
2020,
2,
15,
4,
0,
0,
0
)
basic.forever(function () {
    serial.writeLine("" + (DS3231.year()))
    basic.pause(1000)
})

python:
DS3231.date_time(2020, 2, 15, 4, 0, 0, 0)

def on_forever():
    serial.write_line("" + str((DS3231.year())))
    basic.pause(1000)
basic.forever(on_forever)

**Comment by mworkfun** [comment]
Look at page 11 of the DS3231 data table and set the year table.The register of year is divided into the ten year (high eight bit) and year (low eight bit):

1.(year-2000)/10 ---> takes an integer, ten year

2.(year-2000)/10*16 --> takes an integer, ten year, then moves 8 bits to the left, turning it into a high eight bit data

3.(year-2000)%10 -- the remainder, year, used for the low eighth bit

4.buf[7] = (year-2000)/10*16 + (year 2000)%10 --> Sum of two data, and then writes to register of DS3231.

test IDE:
https://makecode.microbit.org/#editor

java sript:
DS3231.dateTime(
2020,
2,
15,
4,
0,
0,
0
)
basic.forever(function () {
serial.writeLine("" + (DS3231.year()))
basic.pause(1000)
})

python:
DS3231.date_time(2020, 2, 15, 4, 0, 0, 0)

def on_forever():
serial.write_line("" + str((DS3231.year())))
basic.pause(1000)
basic.forever(on_forever)

**Comment by mworkfun** [comment]
Look at page 11 of the DS3231 data table and set the year table.The register of year is divided into the ten year (high eight bit) and year (low eight bit):

1.(year-2000)/10 ---> takes an integer, ten year

2.(year-2000)/10*16 --> takes an integer, ten year, then moves 8 bits to the left, turning it into a high eight bit data

3.(year-2000)%10 -- the remainder, year, used for the low eighth bit

4.buf[7] = (year-2000)/10*16 + (year-2000)%10 --> Sum of two data, and then writes to register of DS3231.

test IDE:
https://makecode.microbit.org/#editor

java sript:
DS3231.dateTime(
2020,
2,
15,
4,
0,
0,
0
)
basic.forever(function () {
serial.writeLine("" + (DS3231.year()))
basic.pause(1000)
})

python:
DS3231.date_time(2020, 2, 15, 4, 0, 0, 0)

def on_forever():
serial.write_line("" + str((DS3231.year())))
basic.pause(1000)
basic.forever(on_forever)

**Pull request closed without merging**
